name: Test run for pull requests
on:
  pull_request:
    branches:
    - main
    - dev

jobs:
  container-job:
    runs-on: ubuntu-latest
    
    container: node:18.14-alpine

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DB: WH_TEST        
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: user
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run e2e tests
        run: yarn test:e2e
        env:
          DB_USER: user
          DB_PASS: pass
          DB_NAME: WH_TEST
          DB_HOST: postgres
          DB_PORT: 5432
      